# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Director' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '~> 2.8.3'
  pod 'Eureka', '~> 3.0.0'
  # Pods for Director

  target 'DirectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DirectorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
